version: "3"

services:
  db:
    container_name: uperg-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    restart: always
  pgadmin:
    container_name: uperg-pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=email@email.com
      - PGADMIN_DEFAULT_PASSWORD=123123
    ports:
      - 5433:80
    depends_on:
      - db
